version: '2'
services:
   mydb:
      image: couchdb:latest
      ports:
      - "5984:5984"
      volumes:
      - ./data/couchdb:/usr/local/var/lib/couchdb
      environment:
         - COUCHDB_USER=admin
         - COUCHDB_PASSWORD=admin
